const eleven = `
<ol><li>Tenganisha kazi ya kuchunguza makosa ya uhalifu na ile ya kupandisha vyeo na kuhakikisha maadili yamezingatiwa katika utumishi wa umma. Kazi ya kuripoti kuhusu kupandisha vyeo na utekelezaji wa maadili itafanywa na Tume iliyopendekezwa ya Maadili inayozungumziwa katika sura ya maadili ya kitaifa.</li>
<li>Bainisha majukumu ya mashirika ya udhibiti ili kuhakikisha kwamba hakuna urudiaji wayo, na kurahisisha uwazi, pawe na huduma za haraka zinazopatikana gharama nafuu ili sheria ya udhibiti ifuatwe kwa viwango vya juu.</li>
<li>Kuimarisha Maabara ya Serikali ili kuifanya iwe imara katika utekelezaji wa majukumu yake.</li>
<li>Unda taasisi madhubuti iliyoungana ya kudhibiti na kuhakikisha usalama wa chakula.</li>
<li>Kaunti ya Nairobi –   Ni kaunti tofauti na nyingine kutokana na ukweli kwamba ndio mji mkuu wa taifa ulio na ofisi za Umoja wa Mataifa (UN). Ofisi za UN jijini Nairobi ni makao makuu ya tatu ya Umoja huo ulimwenguni. Ndio sababu ni tofauti na kaunti nyingine. Wakenya wanaustahi mji huu mkuu kuwa wenye vitengo vyote vikuu vya Serikali na kama eneo muhimu kwa ushiriki wao wa mijadala ya uraia katika maisha ya kitaifa. Hii ina maana kuwa Tume ya Ugavi wa Mapato inaweza kujitahidi kuzingatia hadhi hii maalumu ya Nairobi na mahitaji ya huduma ambayo huja nayo. Zaidi ya kuuzingatia kama mji mkuu, makubaliano ya tarehe 26 Machi 1975 kati ya Jamhuri ya Kenya na Umoja wa Mataifa kuhusiana na makao makuu ya Shirika la Umoja wa Mataifa kuhusu Mazingira jijini Nairobi yanabainisha hatua za Serikali ya Kitaifa kuboresha mazingira, miundo msingi, huduma za umma, na ufikiwaji wa makao makuu haya. Hatua hizi zinakubaliwa na Serikali ya Kitaifa na si Serikali ya Kaunti. Hadhi ya Nairobi kama mwenyeji wa makao makuu ya Umoja wa Mataifa ni sababu kubwa ya kuwa kitovu cha kidiplomasia ambapo nchi kadhaa huanzisha ujumbe maalum ambao huruhusu uwakilishi katika UNEP na mashirika mengine ya UN yanayoendeshwa kutoka Nairobi. Jopokazi linapendekeza kwamba Nairobi ipewe hadhi maalum ya mji mkuu ambao unaipa Serikali ya Kitaifa njia ya kutoa huduma na uwezeshaji ufaao katika kuudumisha kama mji mkuu na kama kitovu cha kidiplomasia. Kwa wakati huo huo, hadhi maalum kama hiyo haifai kuzuia haki za wakazi wa Nairobi za uwakilishwaji katika ngazi za wadi na bunge.</li>
<li>Kuteua Makamishna wa IEBC — Mkutano wa Viongozi wa Vyama Kisiasa Bungeni utateua kwa makubaliano, watu watakaopendekezwa kuteuliwa na Rais kama makamishna wa IEBC. Wanaosaka nafasi hiyo wanapaswa kufikia vigezo vilivyoainishwa katika Katiba na sheria na hawapaswi kuegemea upande wowote, na rekodi ya uadilifu na mambo walioyaafiki, na ambao si wanachama maarufu wa chama cha kisiasa na hawana rekodi ya kuchukua nafasi za umma kwa msaada ya chama.</li>
<li>Makamishna wa muda — Nusu ya Makamishna katika Sura ya 15 kuhusu Tume, isipokuwa kwa IEBC, wanapaswa kuhudumu kwa muda maalum.</li>
<li>Ni sharti kila tume huru iwe na mifumo ya ndani ya uwajibikaji ambayo hutenganisha kwa njia huru na wazi mamlaka ya uteuzi na kupandisha vyeo na yale ya kusimamisha kazi na kusuta.  </li>
<li>Ukaguzi mkali wa mahesabu unaochunguza thamani ya matumizi ya pesa na kuendeleza kanuni bora za usimamizi wa fedha za umma unapaswa kutumika katika kila kitengo cha serikali na kila asasi ya umma.</li>
<li>Kifungu cha 249 (3) kimekiukwa na hii imeathiri uwezo wa Tume za Sura ya 15 na ofisi huru kutekeleza ipasavyo na kwa njia huru majukumu yao. Wakati huo huo, Tume na ofisi huru pia zinapaswa kupitia ukaguzi mkali na mashirika yafaayo ili kuhakikisha kuwa zinatimiza majukumu yao kama inavyotakiwa.</li>
<li>Jumuisha mabaraza ya usimamizi - Hivi sasa, karibu kila sheria   huanzisha mamlaka fulani ya udhibiti au nyingine pia hubuni baraza fulani la rufaa kusuluhisha mambo yanayotokana na zoezi la wadhibiti wa mamlaka yake ya kisheria. Uhusiano kati ya mdhibiti na mabaraza haya umekosesha maana mantiki ya hukumu zisizoegemea upande wowote katika kuamua mizozo. Isitoshe, idadi kubwa ya mabaraza ya hukumu yaliyobuniwa kwa njia huishia kufuja rasilimali za kitaifa pakubwa. Inapendekezwa kuunda Baraza Moja la Rufaa ya Kitaifa ambalo litasikiza na kuamua kesi tofauti za rufaa (kama vile, nguvu na kawi, michezo, na mazingira).</li>
<li>Punguza idadi ya mashirika ya udhibiti kwa kufanya juhudi kubwa za kurahisisha uoanishaji na majukumu yao. Lengo ni kuwa na kanuni chache na zenye kutekelezwa kwa njia bora, na zawadi dhidi ya rushwa katika mchakato huu.</li>
</ol>
`;

export default eleven;
