const one = `<p><span>Wanajopo wa BBI walipokuwa wanazunguka nchini, waligundua matatizo makubwa ambayo yanaathiri suluhisho zilizobainishwa kukabiliana na changamoto maalum. Wanatoa wito kwa kila mmoja kutafakari kwa kina zaidi ikiwa kweli tunataka ufumbuzi wa changamoto zetu zingine ili kujenga Kenya yenye umoja, amani na mafanikio.</span></p><ol>
<li><p><span>TAIFA LA MAADILI DHIDI YA TAIFA LA MAHUSIANO YA DAMU&mdash;Ili Kenya liwe taifa lenye umoja, ni sharti liunganishwe kwa maadili na matamanio ya pamoja wala sio kwa damu na udongo. Taifa lililounganishwa kwa maadili na matamanio ya pamoja hujenga taswira ya matumaini ambayo huboresha mustakabali wa nchi.</span></p></li>
<li><p><span>VIJANA WANAHISI KUTENGWA &mdash; Wakenya wenye umri wa miaka 15-24 huunda asilimia 20.3, zaidi ya wastani wa asilimia 15.8, na wote wanafahamu kuhusu uwezo wao finyu wa kupata nafasi nzuri za kazi. Idadi na ubora wa kazi zinazopatikana kwa vijana wa Kenya ni chache zaidi ya inavyohitajika.</span></p></li>
<li><p><span>MUDA UNAZIDI KUYOYOMEA KWA TAIFA LA KENYA &mdash; Wakenya wanajua kwamba hatuna budi kubadilisha dira, mfumo wetu wa kijamii na kiuchumi, na jinsi tunavyotawaliwa, ikiwa tunataka kuzuia janga kubwa la kutofaulu, lasivyo, tutaendelea kuzama katika lindi la umaskini, unyonge, wasiwasi na migogoro.</span></p></li>
<li><p><span>NI LAZIMA TUOKE KEKI KUBWA ZAIDI YA KITAIFA &mdash; Wanajopo walibaini kutokana na majadiliano yao na Wakenya kwamba maoni ya kisiasa kuhusu ustawi yanajikita zaidi katika kugawana badala ya kuunda. Hali ya kutowiana kwa uchumi wetu wa kitaifa na matamanio ya kibinafsi na ya pamoja ya kujistawisha ni hatari. Jambo moja muhimu zaidi ambalo Serikali yoyote inaweza kufanyia Wakenya ni kuwapa nguvu na uwezo kwa kujenga uchumi uliokwezwa na uundaji wa thamani.</span></p></li>
<li><p><span>WAKENYA HAWAWAJALI WALEMAVU&mdash; Wengi wetu hatuzingatii ulemavu kama kitu ambacho sisi wenyewe tunaweza kukumbwa nacho au kinaweza kuathiri mtu anayetutegemea. Tunahitaji, kwa dharura, kutangamana vyema na watu wenye ulemavu ili waishi kama wanajamii kamili wenye haki na fursa sawa kama ilivyo sawa kimaadili, na kama inavyohakikishwa na Katiba.</span></p></li>
<li><p><span>UKOSEFU WA HAKI KWA VISA VINGI VYA DHULUMA&mdash; Tumechukua mfumo wa kutotendea haki watu wanaodhulumiwa. Kila mwaka, Wakenya wanapitia mateso ya kila aina na dhuluma, ikiwemo wakati wanapotekeleza haki yao ya kisiasa ya kupiga kura. Wao hutafuta haki. Tume huundwa na kuandika ripoti ambazo zinakaa kwenye rafu, pasi na kutekelezwa. Jopokazi linapendekeza kwamba utekelezwaji wa mapendekezo ya ripoti hii, ambayo mengi yana athari kubwa, yanapaswa kujumuisha masilahi na mahitaji ya wahasiriwa wa dhuluma za kihistoria, ikiwa ni pamoja na kuhakikisha kuwa tume zinazotajwa katika kifungu cha 15 zinatekeleza majukumu yazo kuhusu dhuluma za kihistoria ipasavyo.</span></p></li>
</ol>`;

export default one;
