const seven = `
<ol><li>Mkakati wa miaka 50 — Tunahitaji kupanua mawazo yetu yawe ya kudumu ikiwa tunataka kujenga uchumi ambao unakidhi mahitaji ya vizazi vya sasa na vijavyo. Anza na mkakati wa miaka 50 ambao lengo lake kuu ni kuifanya Kenya iwe miongoni mwa mataifa bora zaidi ulimwenguni kwa chumi zilizostawi, za pamoja na endelevu.</li>
<li>Kujenga masoko kana kwamba ni bidhaa za umma — Serikali inapaswa kuwa katika harakati za kuendelea kujenga masoko na kuyapanua masoko hayo kwa ajili ya bidhaa zinazozalishwa na nguvu kazi ya Wakenya katika mataifa jirani kupitia utangamano zaidi.</li>
<li>Kutoa mikopo kwa sekta muhimu — Serikali inapaswa kubuni sera inayotoa miongozo ya kisheria na kiudhibiti kwa benki ili ziweze kutoa mikopo kwa sekta muhimu kama za biashara ndogo ndogo, uuzaji bidhaa nje ya nchi, uzalishaji, makazi, elimu, afya, nishati mbadala, usafi wa mazingira na utupaji wa taka, na kilimo (ikiwemo mifugo na uvuvi).</li>
<li>Ustawi wa viwanda unahitaji kuwa lengo kuu la Serikali – Ni ustawi wa viwanda pekee unaoweza kukuza vipaji vya Wakenya na ni ndoto ya kuendeleza ustawi wa taifa. Ni muhimu kwa Wakenya na Serikali kujitenga na gumzo linaloshamiri kwamba Kenya na mataifa ya Afrika hayawezi kujistawisha kiviwanda kwa sababu ya kasi ya mabadiliko ya kiteknolojia, kwa mfano katika matumizi ya roboti.</li>
<li>Kulinda uvumbuzi wa Wakenya, rasilimali za kinasaba, maarifa ya jadi na misemo kama aina ya mali iliyolindwa kisheria - Mustakabali wa uchumi wa dunia uko katika ubunaji na uvumbuzi kwa kutumia utaalamu wa kiakili, uundaji ramani na matumizi ya msimbo wa kinasaba, na hazina hai ya maarifa ambayo imeandaliwa na vizazi vya jamii zetu.</li>
<li>Akiba ni uwekezaji — Fanya juhudi kubwa ya kuongeza akiba ya kitaifa kwa angalau asilimia 25 ya Pato la Taifa ikiwa Kenya inataka kuendeleza uwezo wake wa kuimarisha uwekezaji katika sekta mbalimbali, kikiwemo kituo cha nguvu kazi madhubuti cha uzalishaji ili kuunda nafasi za kutosha za kazi kwa Wakenya</li>
<li>Mapato kutoka kwa Wakenya waishio ng'ambo-- Usitegemee pesa kutoka ng'ambo pekee bali toa vivutio, kinga na taratibu za kuruhusu Wakenya wanaoishi ng'ambo kuweka zaidi akiba zao nchini Kenya.</li>
<li>Tumia pesa kwa maendeleo, si kwa urasimu pekee - Tumia pesa nyingi kwenye maendeleo kama sehemu ya mapato ya serikali ili kuongeza bidhaa za umma na huduma kwa Wakenya. Lenga uwiano au kikomo cha juu, ulioandikwa kuwa sheria, wa angalau 70:30 kwa maendeleo dhidi ya matumizi ya kawaida.</li>
<li>SRC na mishahara— Ni sharti kuwe na ufafanuzi kuhusu mamlaka ya kisheria na kiutawala ya Tume ya Mishahara na Marupurupu ili kuhakikisha kuwa inasimamia masuala yote yanayohusiana na nyongeza za mishahara.</li>
<li>Ushuru — Ijapokuwa mawanda ya ushuru yanahitaji kupanuliwa ni muhimu kwamba utozaji wa jumla wa ushuru nchini Kenya uwe chini kiasi kwa chumi shindani za kieneo na kimataifa. Wazia mbinu mpya za kurahisisha utozaji ushuru, ikiwemo fikra ya kuanzisha kiwango Sawa cha Ushuru kwa mapato ya juu kuliko ya Mshahara Unaokidhi Mahitaji ya Kimsingi.</li>
<li>Lenga wakulima, wafugaji na wavuvi — Lipe kipaumbele suala la kumaliza ufisadi miongoni mwa wanaotekeleza miradi ya kilimo na ufugaji katika juhudi za kupambana na uovu huo. Imarisha viwanda vya mashambani kama msingi wa kuendeleza aina za kisasa zaidi za uzalishaji.
<ul><li>Kuimarisha Kifungu 43 cha Katiba kuhusu haki za kiuchumi na kijamii</li><li>Serikali ya Kitaifa na Serikali za Kaunti zinapaswa kubuni sera na kanuni za kuongoza utekelezwaji kwa uangalifu wa Kifungu cha 43 cha Haki za Kiuchumi na Kijamii.</li><li>Manifesto za vyama -- Kifungu 43 cha Haki za Kiuchumi na Kijamii kinapaswa kutekelezwa kwa uangalifu na viongozi wote waliochaguliwa na manifesto zote za uchaguzi za vyama vyao vya kisiasa. Hii itahitaji Vyama vyote vya Siasa kuunda maono na sera za utekelezwaji wa Mswada wa Haki (unaojumuisha Haki za Kiuchumi na Kijamii) kama sehemu ya manifesto zao za kampeni za uchaguzi.</li></ul></li>

<li>Hakuna Mkenya ataachwa nje —'Mpango wa Kubadili': Kama sehemu ya kuhakikisha kwamba Wakenya wote wanapata huduma bora ambazo ndio msingi wa kuwaweka watu kwenye njia ya ustawi wa pamoja, Jopokazi linapendekeza 'Mpango wa Kubadili' ili kuyavuta maeneo yaliyotengwa hadi kwenye kiwango bora kinachostahiwa maeneo mengine.
<li>Tumia rasilimali chache za umma kwa maendeleo, si kwa urasimu pekee — Tumia pesa nyingi kwa maendeleo kama sehemu ya mapato ya serikali ili kuongeza bidhaa za umma na huduma kwa Wakenya. Lenga uwiano au kikomo cha juu, ulioandikwa kuwa sheria, wa angalau 70:30 kwa maendeleo dhidi ya matumizi ya kawaida.
<li>Kuza na fungua nafasi kwa vijana ili waonyeshe mipango, ubunifu na ujasiriamali wao— Kwa kuongeza nafasi za ajira na njia za kupata riziki kwa kufanya biashara ndogo ndogo zishindane kwa urahisi na kukua bila Serikali kuziwekea mazingira magumu na ghali kwao kufanya kazi.</li>

<ul>
<li>Taifa liandae na kuzindua mbinu rahisi za wanabiashara wadogowadogo wa Kenya kufanya biashara na kutotegemea vielelezo vya kufanya biashara vinavyoandaliwa na wageni kwa ulinganishi wa kimataifa. Hii inapaswa kuwa tathmini linganishi ya KNBS ya kila mwaka ambayo haijagawanywa kijiografia - kaunti, majiji na miji - na itangazwe.</li>
<li>Punguza kutoza biashara ndogondogo na mpya ushuru kwa kuwapunguzia ushuru kwa angalau miaka saba kama njia ya kuinua ujasiriamali wa vijana na uundaji wa nafasi za kazi.</li>
<li>Ubunifu na michezo — Fanya juhudi za kimakusudi za kuratibu, kuhamasisha na kukuza ubunifu na michezo, miongoni mwa sekta nyingine ambazo vijana wa Kenya huonyesha uwezo mkubwa na ari.</li>
<li>Himiza Sekta ya Kibinafsi kuunda wakfu wa kitaifa, usio wa biashara ambao utasimamiwa na Rais na ambao utatumiwa kutoa ushauri, mafunzo, na zana za kuwasaidia vijana wa miaka 18-35 wanaopania kuwa wafanyabiashara.</li>
<li>Ili kuwasaidia vijana kuanzisha biashara, fungua meza ya ushauri katika kila Kituo cha Huduma Centre kinachosimamiwa na mtaalamu wa maendeleo ya kibiashara.</li>
<li>Kujiajiri na Elimu ya kiufundi — Ni muhimu tuondoe dhana kwamba kazi ya ufundi ni ya wale ambao wameshindwa katika masomo kwa kuunda njia mbili sawa kati ya mafunzo ya kitaaluma na ya ufundi.</li>
</ul>

</ol>`;

export default seven;
