const two = `
<ol><li>Kazi muhimu zaidi ya kitaifa ni kuwazia mambo makubwa na ya kudumu Uchaguzi huja na kuenda na tawala mbalimbali, lakini Kenya itaendelea kuwepo. Tunahitaji maono kuhusu Kenya tunayotaka kuishi katika vizazi vitatu vijavyo au miaka 100. Maono yaliyofumbatwa katika michakato ambayo inaruhusu Wakenya kuyaendeleza zaidi ya chaguzi zinazokuja na kuenda.</li>
<li>Tunapaswa kujipatia historia halisi, inayobadilika, jumuishi na rasmi. Rais Uhuru Kenyatta anapaswa kuagiza Historia rasmi ya Kenya inayorejelea miaka 1000 nyuma na inayotoa maelezo sahihi na halisi&nbsp; kuhusu makazi ya Kenya na wakazi wa sasa; historia zao, historia za uchumi na turathi za makabila yote nchini Kenya; majukumu ya wanawake kihistoria; maelezo kuhusu biashara ya kimataifa ya watumwa na ukoloni; mapambano dhidi ya wakoloni; historia ya kipindi cha baada ya ukoloni katika kila sehemu ya nchi; na historia ya kisasa ikiwemo ile ya maeneo ya mijini na jamii mpya nchini Kenya.</li>
<li>Ni lazima tufurahie ngozi yetu ya Kiafrika&mdash; Jopokazi linapendekeza kwamba Serikali ifanye mipango ya kuoanisha utambulisho wa kisasa wa Wakenya na tamaduni zetu tofauti za Kiafrika ili sisi Waafrika tujisikie vizuri kwenye ngozi yetu na pasiwe na mpaka kati ya hali hizi mbili, au zaidi, wakati mwingine hali kinzani.</li>
<ul><li>Imarisha Wizara ya Utamaduni na Turathi ambayo kwa sasa inaendeshwa na serikali kama shughuli tu ya pembeni.</li><li>Badilisha Siku ya Kufungua Zawadi inayoadhimishwa tarehe 26 Desemba iwe Siku ya Utamaduni Wa Kitaifa kwa kusherehekea utamaduni na kujifunza kuhusu tamaduni zingine za Wakenya (hii inaweza pia kufanywa Januari 1).</li><li>Kukuza heshima ya wazee.</li></ul>

<li>Sisi sote tuna wajibu &mdash; Ni sharti kila sekta kuu ya nchi itekeleze jukumu na wajibu wake kwa umakini zaidi katika kujenga maadili ya kitaifa kutokana na tamaduni tofauti za nchi, masilahi na makundi.</li><li>Kukuza maadili wakati wote &mdash; EACC inapaswa kulenga kukomesha uhalifu wa kiuchumi, na majukumu yake ya maadili yasambaziwe NCIC ambayo kuanzia sasa itabadilishwa jina na kuitwa Tume ya Maadili na majukumu yake yaboreshwe sambamba na mwito wa Tume hiyo, na kwamba iwe chini ya Ofisi ya Rais. Pia:</li>
<ul><li>Kufundisha watoto jinsi ya kutoa huduma na kuwajibika kwa kuanzisha Mtandao wa Kujitolea wa Kitaifa unaounganisha vijana na fursa za kujitolea.</li><li>Kufundisha maadili kama somo la lazima katika mtaala wote wa masomo kutoka nasari hadi chuo kikuu.</li><li>Kujumuisha mafunzo ya maadili na kanuni za kitaifa kama sehemu ya utamaduni wa kila kabila na hususan kama sehemu ya mafunzo wakati wa sherehe za kuingia utu uzima.</li><li>Kutekeleza utaratibu wa sasa wa utekelezwaji sheria chini ya Kifungu kuhusu Uongozi na Uadilifu.</li></ul>

<li>Unganisha amali za kitamaduni na kaida za kisasa za Wakenya kama inavyoonyeshwa katika sherehe za kitamaduni za kuingia utuuzima na maadili na kanuni za Katiba, na Majukumu na Haki za uraia.</li>
</ol>`;

export default two;
